# Generated by Django 4.0.4 on 2022-04-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_alter_otpassword_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
