# Generated by Django 4.0.4 on 2022-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpassword',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
